<footer id="footer">
  <div id="social-wrap">
	 <div id="social-wrap">
  		<ul id="social">
        <li><a href="http://on.fb.me/RuJoOq" TARGET="_blank"><img src="/sites/all/themes/climBootstrap/images/social/facebook_icon.png"></a></li>
        <li><a href="http://bit.ly/TA7qIz" TARGET="_blank"><img src="/sites/all/themes/climBootstrap/images/social/pinterest_icon.png"></a></li>
        <li><a href="http://www.vimeo.com/laurakrudener" TARGET="_blank"><img src="/sites/all/themes/climBootstrap/images/social/vimeo_icon.png"></a></li>
        <li><a href="http://bit.ly/P6It3r" TARGET="_blank"><img src="/sites/all/themes/climBootstrap/images/social/instagram_icon.png" ></a></li>
        <li><a href="http://bit.ly/NjJLcN" TARGET="_blank"><img src="/sites/all/themes/climBootstrap/images/social/twitter_icon.png"></a></li>
        <li><a href="mailto:laura@laurakrudener.com" TARGET="_blank"><img src="/sites/all/themes/climBootstrap/images/social/email_icon.png"></a></li>
       </ul>
  	</div>
  </div>
</footer>