<span id="nav-toggle" href="#"><span></span></span>
<div id="mobile-overlay">
	<div id="mobileNavWrapper">
		<ul>
				<li id="main-nav-items">
					<ul>
						<li><a href="/">Work</a></li>
						<li><a href="/content/about">About</a></li>
					</ul>
				</li>
	      <li>
	        <ul id="social">
	          <li><a href="http://on.fb.me/RuJoOq" TARGET="_blank">Facebook</a></li>
	          <li><a href="http://instagram.com/laurakrudener" TARGET="_blank">Instagram</a></li>
	          <li><a href="http://bit.ly/NjJLcN" TARGET="_blank">Twitter</a></li>
	          <li><a href="http://bit.ly/TA7qIz" TARGET="_blank">Pinterest</a></li>
	          <li><a href="http://www.vimeo.com/laurakrudener" TARGET="_blank">Vimeo</a></li>
	       </ul>
	      </li>
	      <li id="nav-email">
	      	<br>
	      	<a href="mailto: laura@laurakrudener.com">laura@laurakrudener.com</a>
	      </li>	
	    </ul>
	  </div>
</div>

<header class="main">
  <div id="logo">
    <a href="<?php print $front_page; ?>" title="<?php print t('Home'); ?>" rel="home">
      <img src="<?php print $logo; ?>" alt="<?php print t('Home'); ?>"/>
    </a>
  </div>	
</header>		